- 
  activators: 
    - "<option class=\"level-0\" "
    - ">"
  deactivator: <
  limit: 10
  name: options
- 
  activators: 
    - <title>
  deactivator: </title>
  name: title
- 
  activators: 
    - ">Song of the Day: "
  deactivator: <
  limit: -1
  name: songs